/* 컴활 2급 개념카드: 지식, 판별 기준, 기출 연결 규칙 */
window.BWR_CONCEPTS = [
  {"id":"computer-crime","subject":"computer","term":"컴퓨터 범죄와 보안 도구","definition":"백신은 악성코드를 탐지·치료하는 보안 도구입니다. 개인정보 무단 유출, 무단 침입·변조, 허락이나 법적 근거 없는 저작물 이용과 구분합니다.","criterion":"공격·권리 침해인지 정상적인 보호 활동인지 봅니다.","mistake":"공격·권리 침해인지 정상적인 보호 활동인지 봅니다.","match":{"any":["컴퓨터 범죄의 유형"]}},
  {"id":"print-titles","subject":"spreadsheet","term":"인쇄 제목과 반복할 행","definition":"페이지 설정의 시트 탭에서 반복할 행·열을 지정하면 각 인쇄 페이지에 같은 제목을 출력합니다. $3:$3은 3행 하나입니다.","criterion":"인쇄 반복은 인쇄 제목, 화면에서 계속 보기는 틀 고정입니다.","mistake":"인쇄 반복은 인쇄 제목, 화면에서 계속 보기는 틀 고정입니다.","match":{"any":["반복할 행","반복적으로 인쇄"]}},
  {"id":"choose-mid","subject":"spreadsheet","term":"MID와 CHOOSE","definition":"MID(문자열,시작위치,개수)는 지정 위치의 글자를 꺼내고 CHOOSE(번호,값1,값2,…)는 번호에 해당하는 값을 반환합니다.","criterion":"먼저 추출 위치를 세고 그 결과를 선택 번호로 사용합니다.","mistake":"먼저 추출 위치를 세고 그 결과를 선택 번호로 사용합니다.","match":{"any":["CHOOSE(MID"]}},
  {"id":"folder-options","subject":"computer","term":"폴더 옵션과 표시 설정","definition":"폴더 옵션은 숨김 파일 표시·클릭 방식 같은 탐색 동작을 조절합니다. 폴더별 아이콘 변경과 보기 크기는 별도 설정입니다. XP의 파일 형식 탭은 당시 기능입니다.","criterion":"탐색기의 공통 동작과 개별 폴더의 모양을 구분합니다.","mistake":"탐색기의 공통 동작과 개별 폴더의 모양을 구분합니다.","match":{"any":["폴더 옵션","폴더옵션"]}},
  {"id":"chart-editing","subject":"spreadsheet","term":"차트 크기와 원본 데이터","definition":"차트는 원본 데이터로 그립니다. Alt를 누르고 개체 크기를 조절하면 셀 경계에 맞추며 원본 값을 바꾸면 차트가 갱신됩니다. 최신 Excel에서 막대를 드래그해 원본 값을 바꾸는 기능은 제공되지 않습니다.","criterion":"개체의 크기·위치 조절과 원본 데이터 수정은 다릅니다.","mistake":"개체의 크기·위치 조절과 원본 데이터 수정은 다릅니다.","match":{"any":["차트에 대한 설명"]}},
  {"id":"data-validation","subject":"spreadsheet","term":"데이터 유효성 검사","definition":"셀에 허용되는 입력 조건과 오류 알림을 지정합니다. 이미 있는 잘못된 값은 자동 삭제되지 않으며 잘못된 데이터 표시로 확인할 수 있습니다.","criterion":"입력 제한은 기존 값 자동 정리 기능이 아닙니다.","mistake":"입력 제한은 기존 값 자동 정리 기능이 아닙니다.","match":{"any":["유효성 검사"]}},
  {"id":"display-accessibility","subject":"computer","term":"디스플레이와 고대비","definition":"배경·해상도 같은 표시 설정과 접근성의 고대비 설정은 목적이 다릅니다. 고대비는 색 구별을 돕고 해상도를 높이지 않습니다.","criterion":"가독성·접근성 개선과 화면 해상도를 구분합니다.","mistake":"가독성·접근성 개선과 화면 해상도를 구분합니다.","match":{"any":["디스플레이 등록정보"]}},
  {"id":"io-channel","subject":"computer","term":"입출력 채널","definition":"채널은 CPU의 부담을 줄이며 주기억장치와 주변장치 사이의 입출력 전송을 제어합니다. 버퍼는 데이터 임시 저장이고 캐시는 접근 지연 감소가 목적입니다.","criterion":"전송을 제어하는 장치와 임시 저장 공간을 구분합니다.","mistake":"전송을 제어하는 장치와 임시 저장 공간을 구분합니다.","match":{"any":["채널(Channel)"]}},
  {"id":"time-units","subject":"computer","term":"처리시간 단위","definition":"ms=10⁻³초, μs=10⁻⁶초, ns=10⁻⁹초, ps=10⁻¹²초, fs=10⁻¹⁵초, as=10⁻¹⁸초입니다. 같은 작업의 시간이 짧을수록 빠릅니다.","criterion":"빠른 순서는 시간 값이 작은 단위부터입니다.","mistake":"빠른 순서는 시간 값이 작은 단위부터입니다.","match":{"any":["처리시간 단위","처리속도의 단위","처리 속도 단위"]}},
  {"id":"input-output","subject":"computer","term":"입력 장치와 출력 장치","definition":"터치패드·트랙볼은 움직임을 입력하고 OCR은 문자를 인식하여 입력합니다. LCD는 정보를 보여 주는 표시 장치입니다.","criterion":"컴퓨터로 넣으면 입력, 사용자에게 보여 주면 출력입니다.","mistake":"컴퓨터로 넣으면 입력, 사용자에게 보여 주면 출력입니다.","match":{"any":["터치패드","트랙볼"]}},
  {"id":"digital-analog","subject":"computer","term":"디지털과 아날로그","definition":"디지털은 이산적인 값을 부호화해 논리 회로로 처리하고 아날로그는 연속량을 다룹니다. 실제 속도는 작업과 구현에 따라 달라집니다.","criterion":"이산값·논리 회로와 연속량·증폭 회로를 구분합니다.","mistake":"이산값·논리 회로와 연속량·증폭 회로를 구분합니다.","match":{"any":["디지털 컴퓨터의 특성"]}},
  {"id":"windows-shortcuts","subject":"computer","term":"Windows 창 조작 단축키","definition":"Alt+Print Screen은 활성 창 캡처, Alt+Space는 창 제어 메뉴, Alt+Tab과 Alt+Esc는 창 전환입니다. 시작 메뉴는 Windows 키 또는 Ctrl+Esc입니다.","criterion":"전체 화면인지 활성 창인지, 시작 메뉴인지 창 메뉴인지 봅니다.","mistake":"전체 화면인지 활성 창인지, 시작 메뉴인지 창 메뉴인지 봅니다.","match":{"any":["Alt + Print Screen","[Alt]키+[Space bar]"]}},
  {"id":"post-beep","subject":"computer","term":"부팅 경고음의 해석","definition":"POST 경고음은 하드웨어 이상 단서를 주지만 패턴의 뜻은 BIOS·메인보드마다 다릅니다. 일부 ASUS 보드의 긴 1회·짧은 3회는 그래픽 이상을 뜻합니다.","criterion":"기출 정답과 실제 장비의 제조사 설명서를 구분합니다.","mistake":"기출 정답과 실제 장비의 제조사 설명서를 구분합니다.","match":{"any":["길게 한 번 짧게 세 번"]}},
  {"id":"cookies","subject":"computer","term":"쿠키·캐시·방문 기록","definition":"쿠키는 사이트가 브라우저에 저장하도록 한 작은 데이터로 세션 식별·설정 유지 등에 사용됩니다. 캐시는 웹 자원의 재사용, 방문 기록은 방문 URL 목록입니다.","criterion":"사용자 설정·세션은 쿠키, 자원 재사용은 캐시, 방문 목록은 기록입니다.","mistake":"사용자 설정·세션은 쿠키, 자원 재사용은 캐시, 방문 목록은 기록입니다.","match":{"any":["쿠키","Cookie"]}},
  {"id":"chart-types","subject":"spreadsheet","term":"차트 종류와 변수 개수","definition":"거품형은 x·y·크기 세 값을, 분산형은 x·y 관계를 표현합니다. 원형은 한 계열의 구성비, 도넛형은 여러 계열을 고리로 표현합니다.","criterion":"변수 수와 계열 수, 추세·구성비·관계 중 목적을 확인합니다.","mistake":"변수 수와 계열 수, 추세·구성비·관계 중 목적을 확인합니다.","match":{"any":["거품형","여러 데이터 계열이 각각의 고리"]}},
  {"id":"network-attacks","subject":"computer","term":"트랩도어·스니핑·스푸핑·DoS","definition":"트랩도어는 정상 인증을 우회하는 숨은 접근 경로, 스니핑은 통신 엿보기, 스푸핑은 신원·주소 위장, DoS는 서비스 이용을 방해하는 공격입니다.","criterion":"우회 진입·엿보기·위장·서비스 방해 중 행동으로 구분합니다.","mistake":"우회 진입·엿보기·위장·서비스 방해 중 행동으로 구분합니다.","match":{"any":["트랩도어","트랩 도어"]}},
  {"id":"excel-entry","subject":"spreadsheet","term":"Excel 입력 단축키","definition":"Alt+Enter는 셀 안 줄 바꿈, Ctrl+Enter는 선택 영역 동시 입력, Shift+Enter는 입력 확정 후 위쪽 이동입니다. 좁은 열의 날짜는 #으로 표시될 수 있습니다.","criterion":"줄 바꿈·동시 입력·이동의 목적을 구분합니다.","mistake":"줄 바꿈·동시 입력·이동의 목적을 구분합니다.","match":{"any":["여러 셀에 숫자나 문자 데이터를"]}},
  {"id":"freeze-panes","subject":"spreadsheet","term":"틀 고정","definition":"선택한 셀 위쪽 행과 왼쪽 열을 고정합니다. 원하는 고정 범위의 바로 아래·오른쪽 셀을 선택하며 화면 고정은 인쇄 제목과 별개입니다.","criterion":"기준 셀 위·왼쪽이 고정되므로 선택 위치는 아래·오른쪽입니다.","mistake":"기준 셀 위·왼쪽이 고정되므로 선택 위치는 아래·오른쪽입니다.","match":{"any":["틀 고정","틀고정"]}},
  {"id":"sheet-group","subject":"spreadsheet","term":"시트 그룹 입력","definition":"여러 시트를 그룹화하면 셀 입력·편집이 그룹에 포함된 시트의 같은 위치에 함께 적용됩니다. 작업 후에는 그룹을 해제합니다.","criterion":"첫 시트만이 아니라 선택한 모든 시트의 같은 셀이 바뀝니다.","mistake":"첫 시트만이 아니라 선택한 모든 시트의 같은 셀이 바뀝니다.","match":{"any":["시트를 그룹화한 상태"]}},
  {"id":"software-versions","subject":"computer","term":"알파·베타·패치·데모","definition":"알파는 주로 내부 시험, 베타는 정식 출시 전 외부 사용자 평가, 패치는 배포 후 오류 수정·개선, 데모는 홍보·체험이 목적입니다.","criterion":"출시 전후와 시험·수정·홍보라는 목적을 구분합니다.","mistake":"출시 전후와 시험·수정·홍보라는 목적을 구분합니다.","match":{"any":["베타","Beta"]}},
  {"id":"excel-find","subject":"spreadsheet","term":"Excel 찾기·바꾸기","definition":"찾기 옵션은 대소문자·전체 셀 일치·전자/반자 구분 등을 지정합니다. 검색 방향은 행 기준 또는 열 기준으로 선택합니다.","criterion":"행·열 기준 검색 순서와 단순 위·아래 방향을 구분합니다.","mistake":"행·열 기준 검색 순서와 단순 위·아래 방향을 구분합니다.","match":{"any":["전자/반자","전자／반자"]}},
  {"id":"macro-rules","subject":"spreadsheet","term":"매크로 이름과 바로 가기","definition":"매크로 이름은 문자로 시작하고 뒤에 문자·숫자·밑줄을 쓸 수 있으며 공백은 허용하지 않습니다. 소문자 단축키는 Ctrl, 대문자는 Ctrl+Shift와 함께 사용합니다.","criterion":"첫 글자의 숫자와 이름 속 공백은 허용되지 않습니다.","mistake":"첫 글자의 숫자와 이름 속 공백은 허용되지 않습니다.","match":{"any":["매크로 이름","매크로의 이름"]}},
  {"id":"dvd","subject":"computer","term":"DVD의 기록과 용량","definition":"DVD는 CD보다 짧은 파장의 레이저를 사용해 높은 기록 밀도를 얻습니다. 단면 단층은 약 4.7GB이며 DVD-RAM은 반복 기록이 가능합니다.","criterion":"DVD 매체의 기록 가능 여부와 DVD-Video의 압축 규격을 구분합니다.","mistake":"DVD 매체의 기록 가능 여부와 DVD-Video의 압축 규격을 구분합니다.","match":{"any":["DVD는 대용량","DVD-RAM"]}},
  {"id":"disk-cleanup","subject":"computer","term":"디스크 정리와 삭제 대상","definition":"디스크 정리는 임시 파일·캐시·휴지통 등 선택한 불필요한 파일을 삭제하여 사용 가능한 공간을 확보합니다. 저장 장치의 총용량을 늘리거나 파일 배치를 바꾸는 작업은 아닙니다.","criterion":"삭제로 여유 공간 확보는 정리, 파일 재배치는 조각 모음, 이전 시스템 상태로 되돌리기는 복원, 사본 저장은 백업입니다.","mistake":"사용하지 않는 글꼴·응용 프로그램이 자동 삭제되는 것은 아닙니다. 구형 다운로드한 프로그램 파일 항목은 웹 구성 요소 캐시이며 다운로드 폴더 전체와 다릅니다. 항목과 메뉴는 Windows 버전에 따라 달라집니다.","match":{"any":["디스크 정리"],"exclude":["바이러스","유틸리티","실행 속도를 개선"]}},
  {"id":"wearable-computer","subject":"computer","term":"웨어러블 컴퓨터","definition":"웨어러블 컴퓨터는 시계·안경·의복처럼 몸에 착용해 사용하는 컴퓨터입니다. 스마트워치 등이 대표적이며 센서나 음성·동작 인식 기술을 활용할 수 있습니다.","criterion":"몸에 착용하는 사용 형태가 기준입니다. 소형이라는 크기, 인공지능이라는 처리 기술, 서버라는 서비스 역할과 구분합니다.","mistake":"음성·동작 인식만 보고 인공지능 컴퓨터를 고르지 않습니다. 작은 컴퓨터라고 모두 착용형은 아니며 장소에 구애받지 않는다는 표현만으로도 충분하지 않습니다.","match":{"any":["웨어러블","wearable","착용하는 컴퓨터"]}},
  {"id":"cpu-registers","subject":"computer","term":"PC·IR·AC·MAR·MBR","definition":"레지스터는 CPU 내부의 소용량·고속 임시 저장장치입니다. PC는 다음 명령어 주소, IR은 현재 명령어, AC는 연산 결과, MAR은 메모리 접근 주소, MBR(MDR)은 메모리와 주고받는 내용입니다.","criterion":"저장 대상이 다음 명령어의 주소인지 현재 명령어 내용인지 연산 결과인지 구분합니다. PC와 MAR은 모두 주소를 저장하지만 목적이 다릅니다.","mistake":"PC의 Counter를 명령어 개수로 오해하지 않습니다. MAR은 위치, MBR은 그 위치와 주고받는 내용입니다. 레지스터는 RAM보다 용량이 작아도 속도는 빠릅니다.","match":{"any":["레지스터에 관한","레지스터(Register)에 관한","누산기(Accumulator)에 관한","산술논리 연산의 결과","다음 번에 실행할 명령어","앞으로 실행할 명령어의 수","주소와 관련이 없는"]}},
  {"id":"account","subject":"computer","term":"Account와 사용자 식별","definition":"Account는 서비스를 이용하는 사용자의 계정입니다. ID는 계정을 식별하고 비밀번호는 본인임을 확인하는 인증 수단입니다. 계정에는 권한·설정 등의 정보도 연결되므로 단순히 ID와 비밀번호 두 문자열만을 뜻하지는 않습니다.","criterion":"사용자 식별·인증의 기반은 Account, 통신 차단은 Firewall, 요청 중계는 Proxy입니다.","mistake":"Group은 사용자 묶음, Owner는 소유자, Administrator는 관리자 역할입니다. Applet은 과거 웹 페이지에 포함해 실행하던 작은 프로그램을 가리키며 로그인 계정과 다릅니다.","match":{"any":["사용자 ID와 패스워드"]}},
  {"id":"dhcp","subject":"computer","term":"DHCP와 IP 주소 자동 할당","definition":"DHCP는 서버가 클라이언트에 IP 주소를 자동으로 임대하고 서브넷 마스크·기본 게이트웨이·DNS 서버 같은 네트워크 설정도 제공하는 프로토콜입니다. ISP뿐 아니라 가정·회사 네트워크에서도 사용됩니다.","criterion":"IP 주소를 배정하면 DHCP, 이름에 대응하는 주소를 찾으면 DNS 또는 구형 WINS입니다. HTTP는 웹 통신, SMTP는 메일 발송·전달입니다.","mistake":"TCP/IP는 통신 규약의 묶음이므로 주소 자동 할당이라는 구체적 기능의 답은 DHCP입니다. 동적 할당이 매번 반드시 다른 주소를 받는다는 뜻은 아닙니다.","match":{"any":["IP 주소를 동적으로 할당","IP 주소를 자동으로 할당","동적인 IP주소","IP 주소를 자동으로 받을"]}},
  {"id":"virtual-memory","subject":"computer","term":"가상 메모리와 캐시·버퍼","definition":"가상 메모리는 가상 주소를 물리 메모리에 대응시키는 관리 기법입니다. Windows의 페이징 파일은 디스크 공간으로 메모리 요구를 보완합니다. CPU 캐시는 접근 지연 감소, 버퍼는 입출력 임시 저장, 연관 메모리는 내용 검색이 목적입니다.","criterion":"RAM 용량 부족 보완은 가상 메모리, 자주 쓰는 데이터의 접근 속도 개선은 캐시입니다.","mistake":"디스크 용량이나 실제 RAM이 늘지는 않습니다. 잦은 페이지 교환은 느려질 수 있습니다. 페이징 파일은 작업 영구 저장 기능이 아니지만 종료 후 잔여 바이트가 남을 수 있으므로 무조건 지워진다고 단정하지 않습니다.","match":{"any":["가상 메모리","가상메모리","가상 기억장치","가상기억장치"],"exclude":["장치 관리자","장치관리자","제4세대"]}},
  {"id":"disk-maintenance","subject":"computer","term":"디스크 검사·정리·조각 모음","definition":"검사는 파일 시스템 오류 확인·수정, 정리는 불필요한 파일 삭제로 여유 공간 확보, 조각 모음은 HDD의 흩어진 파일 재배치입니다. 검사는 고장 난 장치 자체를 수리하지 않고 조각 모음은 손상 파일 복구나 용량 증가 기능이 아닙니다.","criterion":"오류→검사, 삭제·공간 확보→정리, 단편화·위치 재정렬→조각 모음으로 구분합니다.","mistake":"현재 드라이브 최적화는 매체에 맞는 작업을 선택하며 SSD에는 TRIM 등을 적용합니다. Win98의 자동 검사와 메뉴 경로는 당시 기준이며 HDD의 조각 모음을 SSD에 그대로 적용하지 않습니다.","match":{"any":["디스크 검사","드라이브 최적화","단편화 제거","단편화를 제거","하드디스크 여유 공간","하드디스크의 파일이 손상"]}},
  {"id":"browser-functions","subject":"computer","term":"웹 브라우저의 기능과 시대별 차이","definition":"브라우저는 웹 문서 열람·저장·인쇄와 즐겨찾기 관리를 제공합니다. 예전 브라우저의 메일 프로그램 연동·내장 FTP는 현재 기능과 구분해야 합니다. Chrome·Firefox에서는 내장 FTP가 제거되었습니다.","criterion":"열람·저장·인쇄 기능과 별도 편집 프로그램의 설정을 구분합니다.","mistake":"기출의 FTP 접속 기능을 현재의 보편적 브라우저 기능으로 외우지 않습니다. FTP 프로토콜 자체와 브라우저의 FTP 지원 여부는 별개입니다.","match":{"all":["웹 브라우저의 기능"]}},
  {"id":"internet-services","subject":"computer","term":"IRC·Usenet과 인터넷 서비스","definition":"IRC는 실시간 채팅, Usenet은 뉴스그룹의 게시글·토론, E-mail은 편지 교환, Telnet은 원격 로그인, FTP는 파일 전송입니다. 뉴스그룹은 인터넷 신문과 다르며 보통 NNTP를 이용합니다.","criterion":"실시간 대화인지 게시글 토론인지 먼저 구별하고 로그인·파일 전송·메일의 용도를 나눕니다.","mistake":"뉴스를 신문으로, IRC를 게시판으로 혼동하지 않습니다. Telnet의 역할은 남아 있지만 암호화 원격 접속에는 보통 SSH를 사용합니다.","match":{"any":["IRC","유즈넷","usenet :","usenet -"]}},
  {"id":"notepad-text","subject":"computer","term":"메모장과 일반 텍스트","definition":"Windows XP·7·10의 메모장은 일반 텍스트를 편집하며 기본 확장자는 .txt입니다. 문자열 찾기와 시간·날짜 삽입은 가능하지만 그림·차트의 OLE 개체 삽입이나 문서 내 다양한 서식 저장은 지원하지 않습니다.","criterion":"문자열 입력·검색·저장인지, 서식·그림 개체를 포함한 문서 작성인지로 구분합니다.","mistake":"표시용 글꼴 설정을 문서 자체의 서식 저장과 혼동하지 않습니다. 이 카드는 기출에 나온 Windows 버전을 기준으로 합니다.","match":{"all":["메모장"],"any":["OLE","서식 또는 그래픽","모든 종류의 파일"]}},
  {"id":"notepad-timestamp","subject":"computer","term":"메모장의 F5와 .LOG","definition":"F5 또는 [편집] → [시간/날짜]는 현재 위치에 시각을 한 번 삽입합니다. 첫 줄 맨 왼쪽에 대문자 .LOG를 입력하고 저장하면 파일을 다시 열 때마다 문서 끝에 시간·날짜가 추가됩니다.","criterion":"지금 한 번 넣기는 F5, 파일을 열 때마다 자동 기록하기는 .LOG입니다.","mistake":"NOW()는 메모장 함수가 아닙니다. 메뉴는 삽입이 아니라 편집이며 .LOG의 마침표와 대문자를 지킵니다.","match":{"all":["메모장"],"any":["[F5]","시스템 클럭"]}},
  {"id":"printer-spooling","subject":"computer","term":"프린터 스풀과 인쇄 대기열","definition":"스풀은 인쇄 데이터를 임시 저장하고 대기열로 관리하여 CPU 작업과 출력을 병행하게 합니다. 프린터 자체의 물리적 출력 속도를 높이는 기능은 아닙니다. XP·7에서는 프린터 속성의 고급 탭에서 설정합니다.","criterion":"스풀의 병행 처리와 프린터 기계 성능을 구분합니다. 대기열에서는 작업을 중지·재개·취소하지만 용지 방향·매수 변경은 취소 후 다시 인쇄합니다.","mistake":"전체 문서 스풀 완료 후에만 출력하는 것은 아닙니다. 여러 프린터를 설치해도 기본 프린터는 한 번에 하나이며, 스풀 사용 여부는 추가 마법사가 아니라 설치 후 속성에서 설정합니다.","match":{"any":["스풀","spool"],"exclude":["스풀 에러","인쇄가 안되는","고급] 탭에서 설정할 수 없는","중앙처리 장치 내의 기억장치"]}},
  {id:"storage-units",subject:"computer",term:"기억 용량 단위와 환산",definition:"용량은 Byte → KB → MB → GB → TB → PB 순으로 커집니다. 이 기출의 1024배 관례에서 1GB = 1024³Byte, 1Byte = 8bit입니다. 엄밀한 SI 표기는 1GB = 1000³Byte이고 1024³Byte는 1GiB입니다.",criterion:"용량을 작은 단위로 바꾸면 단계마다 곱하고 큰 단위로 바꾸면 나눕니다. 파일 개수는 같은 단위로 맞춘 전체 용량 ÷ 파일 크기입니다. KB·MB·GB는 처리 속도 단위가 아닙니다.",mistake:"GB에서 Byte까지는 세 단계입니다. 1024²는 MB, 1024⁴는 TB이므로 곱하는 횟수를 셉니다. 2GB = 2048MB, 1KB = 8192bit(1024배 기준)이며 용량의 근삿값을 묻는지 정확한 값을 묻는지도 확인합니다.",match:{any:["Giga Byte","기억용량 단위","KB, MB, GB, TB"]}},
  {id:"grid",subject:"computer",term:"그리드 컴퓨팅",definition:"지리적으로 떨어진 여러 컴퓨터의 자원을 연결해 하나의 고성능 컴퓨터처럼 활용하는 분산 처리 방식입니다.",criterion:"필요한 만큼 서비스를 빌려 쓰면 클라우드, 여러 지역의 계산 자원을 한 작업에 묶으면 그리드입니다.",mistake:"클라우드·분산 컴퓨팅이라는 말만 보고 고르지 말고 자원을 ‘서비스로 이용’하는지 ‘공동 계산에 결합’하는지 확인합니다.",match:{any:["그리드 컴퓨팅","그리드컴퓨팅"]}},
  {id:"cmos",subject:"computer",term:"CMOS",definition:"기출의 전통적 PC 구조에서 CMOS는 시스템 날짜·시간과 부팅 순서, 전원 관리, PnP 같은 설정값을 보관합니다. BIOS 펌웨어 자체는 ROM·플래시에 저장됩니다. 현대 UEFI의 설정은 비휘발성 저장소에 보관될 수 있습니다.",criterion:"설정값을 저장하는 곳은 CMOS, 전원을 켤 때 장치를 검사하는 과정은 POST, 입출력 기본 명령을 제공하는 것은 BIOS입니다.",mistake:"CMOS를 검사 프로그램이나 펌웨어 자체로 오해하기 쉽습니다. 문제에서 ‘설정 저장’인지 ‘부팅 검사’인지 먼저 구분합니다.",match:{any:["CMOS"]}},
  {id:"ipv6",subject:"computer",term:"IPv6",definition:"128비트 주소를 16진수와 콜론(:)으로 표현하는 차세대 인터넷 주소 체계입니다.",criterion:"IPv4는 32비트·10진수·점, IPv6는 128비트·16진수·콜론입니다. 연속된 0은 주소에서 한 번만 ::로 줄입니다.",mistake:"비트 수와 표기법을 서로 바꾸어 놓은 보기가 자주 나옵니다. ‘128·16진수·콜론’을 한 묶음으로 판단합니다.",match:{any:["IPv6","IPV6"]}},
  {id:"bridge",subject:"computer",term:"브리지",definition:"같은 프로토콜을 사용하는 두 LAN을 연결하고 MAC 주소를 기준으로 프레임을 전달하는 장비입니다.",criterion:"리피터는 신호 재생, 브리지는 LAN 구간 연결, 라우터는 IP 경로 선택, 게이트웨이는 서로 다른 체계의 변환·출입구 역할입니다.",mistake:"네트워크 장비를 모두 ‘연결 장치’로 외우면 틀립니다. 판단 단위를 신호·프레임·IP 경로·프로토콜 변환으로 나눕니다.",match:{any:["브리지(Bridge)","브리지"]}},
  {id:"morphing",subject:"computer",term:"모핑",definition:"두 이미지나 3차원 모델 사이의 중간 형태를 생성해 한 대상이 다른 대상으로 부드럽게 변하게 하는 기법입니다.",criterion:"형태가 변하면 모핑, 주요 장면 사이를 보간하면 트위닝, 정지 인형을 조금씩 촬영하면 클레이메이션입니다.",mistake:"단순 이동이나 프레임 보간을 형태 변형과 혼동하지 않습니다. 문제의 핵심 동사가 ‘변한다’인지 ‘움직인다’인지 봅니다.",match:{any:["모핑","Morphing"]}},
  {id:"shareware",subject:"computer",term:"셰어웨어",definition:"기능이나 사용 기간을 제한해 먼저 공개하고 시험 사용 뒤 구매를 유도하는 소프트웨어입니다.",criterion:"무료 사용·배포가 중심이면 프리웨어, 제한된 시험 사용이면 셰어웨어, 오류 수정용 일부 파일이면 패치입니다.",mistake:"인터넷에서 무료로 내려받았다는 사실만으로 프리웨어를 고르면 안 됩니다. 사용 기간·기능 제한 여부가 기준입니다.",match:{any:["셰어웨어","Shareware"]}},
  {id:"restore",subject:"computer",term:"시스템 복원",definition:"복원 지점을 사용해 Windows 시스템 파일과 설정을 이전 상태로 되돌리는 기능입니다.",criterion:"시스템 설정과 설치 프로그램 변화는 되돌릴 수 있지만 개인 문서 백업이나 삭제 파일 복구 기능은 아닙니다.",mistake:"‘복원’이라는 이름 때문에 모든 파일이 돌아온다고 생각하기 쉽습니다. 대상이 시스템 상태인지 개인 데이터인지 구분합니다.",match:{any:["시스템 복원","복원 지점"]}},
  {id:"ransomware",subject:"computer",term:"랜섬웨어",definition:"파일을 암호화하거나 시스템 사용을 막고 복구 대가로 금전을 요구하는 악성 프로그램입니다.",criterion:"자기 복제는 웜, 정보 몰래 수집은 스파이웨어, 키 입력 탈취는 키로거, 접근 차단과 금전 요구는 랜섬웨어입니다.",mistake:"악성코드라는 공통점보다 최종 행동을 봅니다. ‘암호화·잠금·금전 요구’가 함께 나오면 랜섬웨어입니다.",match:{any:["랜섬웨어","Ransomware"]}},
  {id:"pop3",subject:"computer",term:"POP3",definition:"원격 메일 서버에 접속해 받은 메일을 사용자 컴퓨터로 가져오는 수신 프로토콜입니다.",criterion:"메일 보내기는 SMTP, 서버에서 수신 메일 가져오기는 POP3, 서버에 둔 채 동기화하면 IMAP입니다.",mistake:"SMTP와 POP3를 메일 프로토콜이라는 이유로 바꾸어 고르기 쉽습니다. 방향을 ‘보냄·받음’으로 먼저 판단합니다.",match:{any:["POP3"]}},
  {id:"repeater",subject:"computer",term:"리피터",definition:"통신 선로에서 약해지거나 왜곡된 디지털 신호를 증폭·재생해 다시 전달하는 물리 계층 장비입니다.",criterion:"신호 세기를 복원하면 리피터, 프레임을 걸러 LAN을 잇으면 브리지, 최적 IP 경로를 고르면 라우터입니다.",mistake:"전송 거리를 늘린다는 표현과 경로를 선택한다는 표현을 구분합니다. 리피터는 주소를 해석해 길을 고르지 않습니다.",match:{any:["리피터(Repeater)","리피터"]}},
  {id:"ascii",subject:"computer",term:"ASCII",definition:"표준 ASCII는 7비트로 영문 대소문자, 숫자, 문장 부호와 제어 문자를 표현하는 문자 코드입니다.",criterion:"표준 ASCII는 7비트 128개 문자이고, 추가 1비트는 통신 시 패리티나 확장 문자에 사용될 수 있습니다.",mistake:"저장 단위가 1바이트라는 설명 때문에 표준 코드도 8비트라고 판단하지 않습니다. 표준과 확장 ASCII를 구분합니다.",match:{any:["ASCII"]}},
  {id:"vector",subject:"computer",term:"벡터 그래픽",definition:"점·선·곡선의 위치와 관계를 수학적 정보로 저장해 이미지를 표현하는 방식입니다.",criterion:"수학적 도형 정보면 벡터, 픽셀의 색상 정보면 비트맵입니다. 벡터는 확대에 강하고 비트맵은 사진 표현에 유리합니다.",mistake:"모든 벡터 파일이 항상 작다고 단정하지 않습니다. 시험에서는 확대 시 계단 현상과 표현 단위를 우선 판단합니다.",match:{any:["벡터 그래픽","벡터 방식","벡터 이미지","벡터(Vector)"]}},
  {id:"alt-enter",subject:"spreadsheet",term:"Alt + Enter",definition:"Excel 셀에 데이터를 입력하는 중 같은 셀 안에서 강제로 줄을 바꾸는 바로 가기 키입니다.",criterion:"Enter는 입력 완료와 아래 셀 이동, Ctrl+Enter는 선택 영역 동시 입력, Alt+Enter는 한 셀 내부 줄 바꿈입니다.",mistake:"입력 완료 후 셀 이동과 셀 안에서 줄을 바꾸는 동작을 혼동하지 않습니다. 문제에서 ‘같은 셀 안’이 핵심입니다.",match:{any:["Alt> + <Enter","Alt+Enter","Alt] + [Enter","Alt + Enter"]}},
  {id:"vlookup",subject:"spreadsheet",term:"VLOOKUP",definition:"범위의 첫 번째 열에서 값을 찾고 지정한 열 번호의 같은 행 값을 반환하는 함수입니다.",criterion:"정확히 일치하려면 네 번째 인수에 FALSE 또는 0, 근삿값이면 TRUE 또는 1을 사용하며 근삿값 범위는 정렬이 필요합니다.",mistake:"찾을 값이 범위 첫 열에 있어야 한다는 조건과 열 번호가 범위 안에서 센 상대 번호라는 점을 자주 놓칩니다.",match:{any:["VLOOKUP"]}},
  {id:"consolidate",subject:"spreadsheet",term:"데이터 통합",definition:"여러 범위의 데이터를 위치 또는 항목 이름 기준으로 모아 합계·평균·개수 등으로 요약하는 기능입니다.",criterion:"여러 원본 범위를 하나로 요약하면 통합, 한 목록 안에서 그룹별 계산은 부분합, 조건별 결과 비교는 시나리오입니다.",mistake:"‘요약’이라는 말만 보고 부분합을 고르지 않습니다. 원본이 여러 범위인지 하나의 정렬된 목록인지 확인합니다.",match:{any:["데이터 통합","통합 대화상자"]}},
  {id:"sheet-protection",subject:"spreadsheet",term:"시트 보호와 잠금",definition:"셀의 잠금 속성은 시트 보호를 적용했을 때 실제 편집 제한으로 작동합니다.",criterion:"입력을 허용할 셀은 잠금을 먼저 해제하고, 나머지 셀은 잠금 상태로 둔 뒤 시트를 보호합니다.",mistake:"셀에 잠금 속성만 지정했다고 바로 편집이 막히는 것은 아닙니다. 마지막에 시트 보호를 적용해야 효력이 생깁니다.",match:{any:["시트 보호","셀의 잠금","잠금 해제"]}},
  {id:"format-placeholders",subject:"spreadsheet",term:"표시 형식 0 · # · ?",definition:"0은 없는 자리도 0으로 표시하고, #은 유효한 숫자만 표시하며, ?는 숫자가 없어도 자리만 확보합니다.",criterion:"강제 표시 0, 불필요한 0 생략 #, 자릿수 정렬용 공백 ?로 목적을 나누어 판단합니다.",mistake:"#이 숫자가 없을 때 0을 표시한다는 보기가 대표 함정입니다. ‘자리 확보’와 ‘0 표시’를 구분합니다.",match:{any:["사용자 지정 표시 형식","사용자 정의 표시 형식","표시 형식에서"],all:["#"]}},
  {id:"wildcards",subject:"spreadsheet",term:"와일드카드 * · ?",definition:"*는 길이에 관계없는 여러 문자, ?는 임의의 한 문자를 대신하는 검색 기호입니다.",criterion:"문자 수를 정확히 한 자리만 허용하면 ?, 0개 이상 여러 문자를 허용하면 *를 사용합니다.",mistake:"?를 ‘한 글자 이상’으로 외우면 틀립니다. 정확히 한 글자라는 제한과 *의 가변 길이를 비교합니다.",match:{any:["와일드카드","삼?주식회사","임의의 한 문자"]}},
  {id:"date-serial",subject:"spreadsheet",term:"날짜·시간 일련번호",definition:"Excel은 날짜를 기준일부터 센 정수, 시간을 하루를 1로 본 소수로 저장하며 표시 형식만 날짜·시간으로 보여 줍니다.",criterion:"날짜·시간의 내부 값은 숫자이므로 계산할 수 있고 기본적으로 오른쪽 정렬됩니다. 표시 형식 변경은 값 자체를 바꾸지 않습니다.",mistake:"화면에 날짜로 보인다는 이유로 텍스트라고 판단하지 않습니다. 입력값의 저장 형식과 화면 표시를 분리합니다.",match:{any:["날짜와 시간 데이터","날짜 데이터","날짜·시간","날짜의 일련번호","근속일"]}},
  {id:"goal-seek",subject:"spreadsheet",term:"목표값 찾기",definition:"수식 결과가 원하는 값이 되도록 그 수식이 참조하는 하나의 입력 셀 값을 역으로 계산하는 도구입니다.",criterion:"하나의 결과와 하나의 변경 셀을 역산하면 목표값 찾기, 여러 입력 조합을 저장·비교하면 시나리오입니다.",mistake:"변경 셀에는 수식이 아니라 조정 가능한 입력값이 있어야 합니다. 여러 변수를 동시에 찾는 기능으로 오해하지 않습니다.",match:{any:["목표값 찾기"]}},
  {id:"advanced-filter",subject:"spreadsheet",term:"고급 필터 조건",definition:"복잡한 조건 범위를 별도로 작성해 목록을 필터링하거나 다른 위치에 결과를 복사하는 기능입니다.",criterion:"조건 범위에서 같은 행은 AND, 서로 다른 행은 OR이며 필드명은 원본 목록의 필드명과 정확히 같아야 합니다.",mistake:"일상 언어의 줄바꿈과 논리 관계를 반대로 생각하기 쉽습니다. 한 행에서 동시에 만족하면 AND로 기억합니다.",match:{any:["고급 필터"]}},
  {id:"rank-eq",subject:"spreadsheet",term:"RANK.EQ",definition:"목록에서 지정한 값의 순위를 구하며 같은 값에는 같은 순위를 부여하는 함수입니다.",criterion:"세 번째 인수가 0 또는 생략이면 큰 값이 1위인 내림차순, 1이면 작은 값이 1위인 오름차순입니다.",mistake:"정렬 방향 인수를 반대로 외우거나 복사할 참조 범위를 고정하지 않는 실수가 많습니다. 순위 기준 범위는 보통 절대 참조합니다.",match:{any:["RANK.EQ","RANK(","RANK 함수"]}},
  {id:"pivot",subject:"spreadsheet",term:"피벗 테이블",definition:"많은 데이터를 행·열·필터·값 필드로 재배치해 원하는 관점으로 요약하고 분석하는 도구입니다.",criterion:"원본 데이터는 유지한 채 요약 배치를 바꾸며, 원본이 변경되면 새로 고침해야 결과에 반영됩니다.",mistake:"피벗 테이블을 삭제하거나 필드를 옮겨도 원본 데이터가 삭제되는 것은 아닙니다. 원본과 요약 결과를 분리합니다.",match:{any:["피벗 테이블","피벗테이블"]}},
  {id:"countif-average",subject:"spreadsheet",term:"COUNTIF + AVERAGE",definition:"AVERAGE로 기준값을 구하고 COUNTIF의 조건 문자열과 &로 연결하면 평균 이상·이하 값의 개수를 셀 수 있습니다.",criterion:"비교 연산자는 문자열 안에 쓰고 계산된 기준값은 &로 결합합니다. 예: =COUNTIF(C2:C8,\">=\"&AVERAGE(C2:C8)).",mistake:"\">=AVERAGE(...)\" 전체를 문자열로 쓰면 함수가 계산되지 않습니다. 연산자 문자열과 함수 결과의 경계를 구분합니다.",match:{all:["COUNTIF","AVERAGE"]}}
];

window.BWR_CONCEPT_MATCH = (concept, question) => {
  if (concept.subject && question.subject !== concept.subject) return false;
  const haystack = [question.q, ...(question.c || []), question.e].join(" ").toLowerCase();
  const any = concept.match?.any || [];
  const all = concept.match?.all || [];
  const exclude = concept.match?.exclude || [];
  const hasAny = !any.length || any.some((term) => haystack.includes(String(term).toLowerCase()));
  const hasAll = all.every((term) => haystack.includes(String(term).toLowerCase()));
  const hasExcluded = exclude.some((term) => haystack.includes(String(term).toLowerCase()));
  return hasAny && hasAll && !hasExcluded;
};
